[RUCIO-1858] Check if git rebase master is possible, give an error otherwise

diff --git a/tools/create-feature-branch b/tools/create-feature-branch
--- a/tools/create-feature-branch
+++ b/tools/create-feature-branch
@@ -16,6 +16,10 @@ git pull --all --prune --progress
 
 echo "Rebasing next"
 git rebase upstream/next next
+if [ $? ]; then
+    echo "Can't rebase to master. Unstaged changes?"
+    exit 1
+fi
 
 echo "Creating feature branch"
 git checkout -b feature-$1-${2//[^a-zA-Z0-9]/_} next
