self-testing new submit-review ; this should have worked
Change-Id: I3d1e148b51f9e67a0276dd383dcb061c32f503cd

diff --git a/tools/submit-review b/tools/submit-review
--- a/tools/submit-review
+++ b/tools/submit-review
@@ -9,12 +9,11 @@
 # Authors:
 # - Mario Lassnig (CERN PH-ADP), <mario.lassnig@cern.ch>, 2006-2011
 
-
 usage() {
     echo "usage: submit-review [-h/--help] [-d/--dry] [-a/--amend <message>]"
     echo
     echo This submits the currently commited local master to gerrit for review.
-    echo If you want to amend the previous commit, give the new amend commit message as an optional argument.
+    echo If you want to amend the previous commit, give the new amend commit message as an argument.
     echo
     echo Use the --dry run to validate without submitting.
     echo
@@ -47,19 +46,21 @@ push_commit() {
             echo You are missing the amend message, e.g.: tools/submit-review -a \"now it is fixed\"
             exit 2
         fi
+        cmt=`git log -1 --pretty=oneline | cut -d" " -f1`
+        msg=`git log -1 --pretty=oneline | cut -d" " -f2-`
         cid=`git log -1 | grep Change-Id: | awk '{print $2;}'`
-        echo Amending previous commit with Change-Id: $cid and Comment: $BASH_ARGV
-        $dry git commit -a --amend -m "$BASH_ARGV
+        echo Amending commit $cmt
+        $dry git commit -a --amend -m "$msg ; $BASH_ARGV
 
 Change-Id: $cid"
         if [ ! $? -eq 0 ] ; then
-            echo "FATAL amend did not work! Aborting."
+            echo "FATAL! Amend did not work! Aborting."
             exit 1
         fi
     fi
     $dry git push origin HEAD:refs/for/master
     if [ ! $? -eq 0 ] ; then
-        echo "FATAL push did not work! Aborting."
+        echo "FATAL! Push did not work! Aborting."
         exit 2
     fi
 }
@@ -70,8 +71,11 @@ main() {
 
     branch="$(git branch 2>/dev/null | sed -e "/^\s/d" -e "s/^\*\s//")"
     if [[ "$branch" == "master" ]]; then
+        echo 'You want to push a master commit, that is not good practice.'
         echo 'Create new local branch and switch to it. E.g.:'
-        echo 'git checkout -b new_feature'        
+        echo 'git checkout -b new_feature'
+        echo 'Make the change there, and submit from the branch.'
+        exit 1
     else
 
         if [[ "$@" == *-d* ]]; then
