Testing:upload/download and xrd integration tests #2311 (#4165)
* #2311 
* #2311 return lfn_dict if already valid, in file: lib.rucio.common.make_valid_did
* #2311 set attributes for xrd test containers and misc workarounds
* #2311 rucio server upload/download tests
* #2311 stop containers in gh action workflow
* #2311 port xrd tests to python3
* #2311 python3 changes for xrootd.py, fix arguments for methods in rsemanager.py
* cleanup #2311
* Testing: fix ci errors #2311
* Testing: build and cache rucio-dev images #2311
* Testing: enable protocol tests only in CI #2311
* Testing: imagecaching for image used by integration tests #2311
* Testing: filter matrix in e2e test workflow #2311
* Testing: filter matrix in autotest, build image in e2e tests #2311
* Testing: Use jq to extract e2e test matrix #2311
* Testing: change image building and caching in e2e workflow #2311
* Testing: fix matrix for autotests #2311
* Testing: fix jq filtering for matrix in autotest workflow #2311
* Testing: change pytest args #2311
* Testing: revert autotest workflow #2311
* Testing: refactor build_images and autotests #2311
* Testing: refactor build_images, add new matrix #2311
* Testing: add integration_test image identifier #2311
* Testing: remove integration_test suite from autotest matrix #2311
* Testing: cleanup debug code in build_images.py #2311
* Testing: cleanup debug code in build_images.py #2311
* Testing: debug autotests #2311
* Testing: fix integration-tests #2311
* Testing: use rucio/containers for e2e tests #2311
* Testing: remove integration_test suite from autotest matrix #2311
* Testing: cleanup GH workflows #2311
* Testing: cleanup GH workflows #2311

diff --git a/.github/workflows/imagecache.yml b/.github/workflows/imagecache.yml
--- a/.github/workflows/imagecache.yml
+++ b/.github/workflows/imagecache.yml
@@ -6,7 +6,7 @@ on:
     - cron: '0 3 * * 1-5'
 
 jobs:
-  build:
+  build_autotests:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
@@ -26,6 +26,41 @@ jobs:
             IMAGES=$(echo '${{ steps.matrix.outputs.matrix }}' | ./tools/test/build_images.py --output list \
                 --build-no-cache --cache-repo docker.pkg.github.com/${{ github.repository }} --push-cache \
                 ./etc/docker/test || echo "")
+            if [[ -n $IMAGES ]]; then break;
+            else
+              i=$((i+1)); sleep 5;
+              echo "::warning::Building images failed, retrying…"
+            fi
+          done
+          docker logout https://docker.pkg.github.com
+          if [[ -z $IMAGES ]]; then echo "::error::Building images failed ultimately"; exit 1; fi
+  build_integration_tests:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout rucio containers repository
+        uses: actions/checkout@v2
+        with:
+          repository: rucio/containers
+      - name: Checkout rucio source
+        uses: actions/checkout@v2
+        with:
+          path: dev/rucio
+      - name: Update pip
+        run: python3 -m pip install -U pip setuptools
+      - name: Install python requirements for matrix_parser.py
+        run: python3 -m pip install -U PyYAML
+      - name: Identify Matrix
+        id: matrix
+        run: echo "::set-output name=matrix::$(${{ github.workspace }}/dev/rucio/tools/test/matrix_parser.py < ${{ github.workspace }}/dev/rucio/etc/docker/test/matrix_integration_tests.yml)"
+      - name: Build and upload images
+        id: images
+        shell: bash
+        run: |
+          docker login https://docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
+          i=0; until [ "$i" -ge 3 ]; do
+            IMAGES=$(echo '${{ steps.matrix.outputs.matrix }}' | ${{ github.workspace }}/dev/rucio/tools/test/build_images.py --output list \
+                --build-no-cache --cache-repo docker.pkg.github.com/${{ github.repository }} --push-cache \
+                ${{ github.workspace }}/dev || echo "")
             if [[ -n $IMAGES ]]; then break;
             else
               i=$((i+1)); sleep 5;
