Testing: refactor build_images, add new matrix #2311

diff --git a/.github/workflows/imagecache.yml b/.github/workflows/imagecache.yml
--- a/.github/workflows/imagecache.yml
+++ b/.github/workflows/imagecache.yml
@@ -6,7 +6,7 @@ on:
     - cron: '0 3 * * 1-5'
 
 jobs:
-  build:
+  build_autotests:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
@@ -17,6 +17,34 @@ jobs:
       - name: Identify Matrix
         id: matrix
         run: echo "::set-output name=matrix::$(./tools/test/matrix_parser.py < ./etc/docker/test/matrix.yml)"
+      - name: Build and upload images
+        id: images
+        shell: bash
+        run: |
+          docker login https://docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
+          i=0; until [ "$i" -ge 3 ]; do
+            IMAGES=$(echo '${{ steps.matrix.outputs.matrix }}' | ./tools/test/build_images.py --output list \
+                --build-no-cache --cache-repo docker.pkg.github.com/${{ github.repository }} --push-cache \
+                ./etc/docker/test || echo "")
+            if [[ -n $IMAGES ]]; then break;
+            else
+              i=$((i+1)); sleep 5;
+              echo "::warning::Building images failed, retrying…"
+            fi
+          done
+          docker logout https://docker.pkg.github.com
+          if [[ -z $IMAGES ]]; then echo "::error::Building images failed ultimately"; exit 1; fi
+  build_integration_tests:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+      - name: Update pip
+        run: python3 -m pip install -U pip setuptools
+      - name: Install python requirements for matrix_parser.py
+        run: python3 -m pip install -U PyYAML
+      - name: Identify Matrix
+        id: matrix
+        run: echo "::set-output name=matrix::$(./tools/test/matrix_parser.py < ./etc/docker/test/matrix_integration_tests.yml)"
       - name: Build and upload images
         id: images
         shell: bash
